### ISSUE TITLE
Không nên SELECT * khi UNION

### ISSUE THREAD

**Issue by ducchetrongminh** [devil6789/DWH_project#2]
Khi UNION thì không nên SELECT * vì sẽ dễ bị lộn thứ tự cột nha. Với lại em SELECT 1 hàng như dòng 148 là khỏi sửa luôn á 🥲

https://github.com/devil6789/DWH_project/blob/1e56709c6664daead8693179a0888853b34615ba/models/analytics/dim_customer.sql#L143-L151

**Comment by devil6789** [comment]
Vâng em hiểu ý anh rồi
