### ISSUE TITLE
Đặt tên

### ISSUE THREAD

**Issue by ducchetrongminh** [devil6789/DWH_project#5]
Công thức là `ordered_outers * expected_unit_price_per_outer` thì nên đặt tên là ordered_expected_price chứ hả, vì nó đâu còn outer ở trong này. Thiệt ra là nên đặt ordered_amount hay s đó kiểu v, vì đây hết là price rồi mà là tổng số tiền rồi nè.

https://github.com/devil6789/DWH_project/blob/1e56709c6664daead8693179a0888853b34615ba/models/analytics/fact_purchase_order_line.sql#L94

**Comment by devil6789** [comment]
Vâng để e sửa lại
