### ISSUE TITLE
Handle null lạ

### ISSUE THREAD

**Issue by ducchetrongminh** [devil6789/DWH_project#8]
Chỗ handle null này sao a thấy lạ lạ v?

https://github.com/devil6789/DWH_project/blob/1e56709c6664daead8693179a0888853b34615ba/models/analytics/fact_sales_order_line.sql#L72-L81

**Comment by devil6789** [comment]
Ý em là: Chuyển NULL về 0, còn những giá trị key lỗi thì chuyển về -1
